config/routes.rb
Rails.application.routes.draw do
  

  controllers = {
      :registrations      => "registrations",
      :sessions           => "sessions"
  }

  devise_for :users , :controllers => controllers

  resources :survey do
  	resources :feedbacks
  end

  root 'home#index'

  # get 'questions/index' , :as => "questions"

  # get 'dashboard/index', :as => "dashboard"

end

app/models/survey.rb
class Survey < ActiveRecord::Base


  has_many :questions , :class_name => "Question" , :dependent => :destroy
  accepts_nested_attributes_for :questions ,  :allow_destroy => true , :reject_if => lambda { |a| a[:text].blank? }


  has_many :feedbacks , :class_name => "Feedback" , :dependent => :destroy
  accepts_nested_attributes_for :feedbacks ,  :allow_destroy => true

  has_many :options , :through => :questions


  validates :title , :presence => true , :length => {:minimum => 1 ,:maximum => 100 }
  validates :description, :presence => true , :length => {:minimum => 1 , :maximum => 250 }

  # validates :questions , :presence => true

end

app/controllers/survey_controller.rb
class SurveyController < ApplicationController

  before_action :authenticate_user! , :authenticate_admin

  def index
  end

  def new
    @survey = Survey.new
    @types = Question.types
    4.times { @survey.questions.build }
  end

  def create

    @survey = Survey.new survey_params
    @types = Question.types

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @survey = Survey.find_by_id params[:id]
    @types = Question.types
  end

  def edit
    @survey = Survey.find_by_id params[:id]
    @types = Question.types
  end

  def update
    @survey = Survey.find_by_id(params[:id])
    @types = Question.types

    respond_to do |format|
      if @survey.update_attributes survey_params
        format.html { redirect_to @survey }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @survey = Survey.find_by_id(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to survey_index_path }
    end
  end

  private
  def survey_params
    params.require(:survey).permit!
  end
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/views/survey/_survey_form.html.erb
<% 
  path = @survey.new_record? ? survey_index_path : survey_path 
%>

<div class="container paper">


<% if @survey.errors.any? %>
  <div class="alert alert-error" style="margin-top:10px;">
    <h3>Resolve the issues and try again </h3>
    <% @survey.errors.messages.each do |key,value| %>
       <% value = ["You should create atleast one option if you have selected a Multiple choice Question "] if key == "questions.options" %>
      <span><b><%= "#{key}:" %></b> <%= "#{value.join(",")}"  %></span><br/>
    <% end %>
</div>
<% end %>


<div style="padding-top:20px;padding-bottom:50px;margin-left:40px;">


   

    <%= simple_nested_form_for(@survey, :as => :survey , :url => path , :html => {:class => "form-signin" , :style=>"max-width:80%;"} ) do |f| %>
        
            
      <%= f.input :title, :input_html=> { :class=> "form-control" ,:style=>""}, :required => true, :placeholder=>"Title" %>

      
    <%= f.input :description, :required => true, :as => :text , :placeholder=>"Description", input_html: { :class=> "form-control"} %>
      
      
   <div style="background-color:#f1f1f1;padding:10px;margin-top:10px;">
     <h4>Add Questions</h4>

      
        <%= f.fields_for(:questions , :input_html => {:style=>""}) do |q|  %>

        <div style="background-color:#cdcdcd;margin:10px;padding:10px;">
            <%= q.input :text, :label => false , :required => true, :placeholder=>"Question ", input_html: { :class=> "form-control" } %>

            <%= q.input :type, :required => true, :as => :select, :label=>false, :collection =>@types, :prompt => "Select your Question Type",:input_html=>{  :onchange => "", :class=> "form-control" , :style=>"width:50%;"} %>
            
            <%= q.link_to_remove "Remove this Question"  %>  

              <%= q.fields_for :options do |o| %>
            
              <div style="background-color:#bdbdbd;margin:5px;padding:10px;" >
                  <%= o.input :value, :label => false , :required => true, :placeholder=>"* Option ", input_html: { :class=> "form-control"} %>

                  <%= o.link_to_remove "Remove this Option" %>
              </div>
            
          <% end %>

          <%= q.link_to_add "Add Option to this Question", :options  , :style => "margin-left:20px;"%>
          
          </div>
            <% end %> 
        

            <%= f.link_to_add "Add new Question", :questions %>
          
        </div>

         <%= f.submit "Create Survey", :class=>"btn btn-lg btn-primary", :style=>"margin-top:30px; ", "data-loading-text"=>"Signing In..." %>
       
    <% end %>

</div>
</div>

app/views/survey/edit.html.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active"><%= link_to "All Surveys" , survey_index_path %></li>
  <li class="active"><%= @survey.title %></li>
</ol>

<h1>Edit Survey</h1>
   
<%= render :partial => "/survey/survey_form" %>

app/views/survey/index.html.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active">Surveys</li>
</ol>

<h1>All Surveys</h1>


<div class="container">

<%= link_to "create Survey" , new_survey_path , :class=>"btn btn-medium btn-success" ,:style=>"float:right;margin-top:-35px;margin-right:20px;" %>




<% Survey.all.each do |survey| %>
<div class="well min-survey">
 	<h4 align="center"><%= survey.title %></h4>
 	<div style="padding-top:50px;">
		<%= link_to "show" , survey_path(:id => survey.id) %> 
		<%= link_to "edit" , edit_survey_path(:id => survey.id) ,:style=>"margin-left:25px;"%> 
		<%= link_to "delete" , survey_path(:id => survey.id) , :method => :delete , :data_confirm => 'Are you sure?',:style=>"margin-left:25px;"%>
	</div> 
</div>

<% end %>

app/views/survey/new.html.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active"><%= link_to "All Surveys" , survey_index_path %></li>
  <li class="active">New Survey</li>
</ol>

<h1 style="color:#fff;">Create New Survey</h1>
   
<%= render :partial => "/survey/survey_form" %>

app/views/survey/show.html.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active"><%= link_to "All Surveys" , survey_index_path %></li>
  <li class="active"><%= @survey.title %></li>
</ol>



<div class="container paper">

<h1 style="color:#666"><%= @survey.title %></h1>


<%= link_to "Delete" , survey_path(:id => @survey.id) , :method => :delete , :class=>"pull-right", :confirm => "Are you sure?" ,:style=>"margin-left:25px;"%>

<%= link_to "Edit" , edit_survey_path(:id => @survey.id) ,:class=>"pull-right",:style=>"margin-left:25px;"%> 

<%= link_to 'Show all Responses', survey_feedbacks_path(@survey) , :class=> "pull-right "%>


<div style="margin-left:40px;">

<p><b><%= "{ #{@survey.description} }" %></b></p>

<h2>Questions</h2>

<% @survey.questions.each_with_index do |question,index| %>

	<h4><%= "#{index+1}, #{question.text}" %></h4>

	   <div style="margin-left:30px;font-style:italic;"><%= "Options:  #{question.option_list.join(",")}"  if question.options.any? %></div>

<% end %>

</div>
</div>